/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChemistryIndexRouteImport } from './routes/chemistry.index'
import { Route as ChemistryChapterRouteImport } from './routes/chemistry.$chapter'
import { Route as MathematicsIndexRouteImport } from './routes/mathematics.index'
import { Route as MathematicsChapterRouteImport } from './routes/mathematics.$chapter'
import { Route as PhysicsIndexRouteImport } from './routes/physics.index'
import { Route as PhysicsChapterRouteImport } from './routes/physics.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChemistryIndexRoute = ChemistryIndexRouteImport.update({
  id: '/chemistry/',
  path: '/chemistry/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChemistryChapterRoute = ChemistryChapterRouteImport.update({
  id: '/chemistry/$chapter',
  path: '/chemistry/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const MathematicsIndexRoute = MathematicsIndexRouteImport.update({
  id: '/mathematics/',
  path: '/mathematics/',
  getParentRoute: () => rootRouteImport,
} as any)
const MathematicsChapterRoute = MathematicsChapterRouteImport.update({
  id: '/mathematics/$chapter',
  path: '/mathematics/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicsIndexRoute = PhysicsIndexRouteImport.update({
  id: '/physics/',
  path: '/physics/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicsChapterRoute = PhysicsChapterRouteImport.update({
  id: '/physics/$chapter',
  path: '/physics/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/chemistry/$chapter': typeof ChemistryChapterRoute
  '/mathematics/$chapter': typeof MathematicsChapterRoute
  '/physics/$chapter': typeof PhysicsChapterRoute
  '/chemistry/': typeof ChemistryIndexRoute
  '/mathematics/': typeof MathematicsIndexRoute
  '/physics/': typeof PhysicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/chemistry/$chapter': typeof ChemistryChapterRoute
  '/mathematics/$chapter': typeof MathematicsChapterRoute
  '/physics/$chapter': typeof PhysicsChapterRoute
  '/chemistry': typeof ChemistryIndexRoute
  '/mathematics': typeof MathematicsIndexRoute
  '/physics': typeof PhysicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/chemistry/$chapter': typeof ChemistryChapterRoute
  '/mathematics/$chapter': typeof MathematicsChapterRoute
  '/physics/$chapter': typeof PhysicsChapterRoute
  '/chemistry/': typeof ChemistryIndexRoute
  '/mathematics/': typeof MathematicsIndexRoute
  '/physics/': typeof PhysicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/chemistry/$chapter'
    | '/mathematics/$chapter'
    | '/physics/$chapter'
    | '/chemistry/'
    | '/mathematics/'
    | '/physics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/chemistry/$chapter'
    | '/mathematics/$chapter'
    | '/physics/$chapter'
    | '/chemistry'
    | '/mathematics'
    | '/physics'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/chemistry/$chapter'
    | '/mathematics/$chapter'
    | '/physics/$chapter'
    | '/chemistry/'
    | '/mathematics/'
    | '/physics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ChemistryChapterRoute: typeof ChemistryChapterRoute
  MathematicsChapterRoute: typeof MathematicsChapterRoute
  PhysicsChapterRoute: typeof PhysicsChapterRoute
  ChemistryIndexRoute: typeof ChemistryIndexRoute
  MathematicsIndexRoute: typeof MathematicsIndexRoute
  PhysicsIndexRoute: typeof PhysicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chemistry/': {
      id: '/chemistry/'
      path: '/chemistry'
      fullPath: '/chemistry/'
      preLoaderRoute: typeof ChemistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chemistry/$chapter': {
      id: '/chemistry/$chapter'
      path: '/chemistry/$chapter'
      fullPath: '/chemistry/$chapter'
      preLoaderRoute: typeof ChemistryChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mathematics/': {
      id: '/mathematics/'
      path: '/mathematics'
      fullPath: '/mathematics/'
      preLoaderRoute: typeof MathematicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mathematics/$chapter': {
      id: '/mathematics/$chapter'
      path: '/mathematics/$chapter'
      fullPath: '/mathematics/$chapter'
      preLoaderRoute: typeof MathematicsChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics/': {
      id: '/physics/'
      path: '/physics'
      fullPath: '/physics/'
      preLoaderRoute: typeof PhysicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics/$chapter': {
      id: '/physics/$chapter'
      path: '/physics/$chapter'
      fullPath: '/physics/$chapter'
      preLoaderRoute: typeof PhysicsChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ChemistryChapterRoute: ChemistryChapterRoute,
  MathematicsChapterRoute: MathematicsChapterRoute,
  PhysicsChapterRoute: PhysicsChapterRoute,
  ChemistryIndexRoute: ChemistryIndexRoute,
  MathematicsIndexRoute: MathematicsIndexRoute,
  PhysicsIndexRoute: PhysicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
